main: server.alanbecker.net.Main
name: ABMCChatFilter
version: 1
api-version: 1.19
folia-supported: true
commands:
  abmcswear:
    description: Toggles the visibility of swear words in chat.
    usage: /<command>

